echo "Trump: I will make America great again!"
echo "Iran: We will not be intimidated by your threats."
echo "Trump: We will impose sanctions on your country."
echo "Iran: We will continue to defend our sovereignty."
echo "Trump: We will work with our allies to isolate Iran."
echo "Iran: We will seek support from our regional partners."
echo "Trump: We will not back down from our position."
echo "Iran: We will not be bullied by your administration."
echo "Trump: We will continue to pressure Iran until they change their behavior."
echo "Iran: We will not compromise our principles for the sake of appeasement."
echo "Trump: We will continue to pursue a maximum pressure campaign."
echo "Iran: We will continue to resist your attempts to undermine our government."