#!/usr/bin
echo "All variables passed to the script are: $*"
echo "The first variable passed to the script is: $1"
echo "The number of variables passed to the script is: $#"
echo "The script name is: $0"
echo "The user running the script is: $USER"
echo "The home directory of the user is: $HOME"
echo "The current working directory is: $PWD"
echo "The process ID of the script is: $$"
echo "The exit status of the last command is: $?"
echo "The last background command's process ID is: $!"
echo "The current shell is: $SHELL"
echo "The current shell level is: $SHLVL"
echo "The current terminal is: $TERM"
echo "The current path is: $PATH"
echo "The current hostname is: $HOSTNAME"
echo "The current date and time is: $(date)"
echo "The current user ID is: $UID"
echo "The current group ID is: $GID"
echo "The current effective user ID is: $EUID"
echo "The current effective group ID is: $EGID"
echo "The current process group ID is: $PGID"
echo "The current session ID is: $SID"
echo "The current terminal type is: $OSTYPE"
echo "The current shell options are: $-"
echo "The current shell version is: $BASH_VERSION"
echo "The current shell name is: $BASH"
